### ISSUE TITLE
[Suggestion]: Wormhole painting

### ISSUE THREAD

**Issue by MagmaForce3400** [Mrbysco/Dimensional-Paintings#11]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

This painting wouldn't look like a dimension but more like a wormhole, since it's one. By placing two wormhole paintings in the same dimension, they will link eachother and you will be able to go from point A to point B.
![download](https://user-images.githubusercontent.com/113281362/194919252-1b8871d4-d51f-4273-a9df-a8bbb6503c15.jpg)
It would look something like this

**Comment by Mrbysco** [comment]
Adding such feature would open a can of worms of "what if you're playing on a multiplayer server? will you not be able to have more than 2?" And it doesn't fit the idea of the mod.
