### ISSUE TITLE
[Bug]: Dimensional Paintings don't teleport to Nether/End

### ISSUE THREAD

**Issue by ShadowDeltaQ** [Mrbysco/Dimensional-Paintings#12]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

36.2.39

### Mod version

Dimensional-Paintings-1.16.5-1.2.1.jar

### Java version

Java 8 update 351

### Issue Description

I was doing a playtest of my custom modpack when I tried to reach the Nether using the corresponding painting. The moment I jumped in the classic "Loading terrain..." appears but for some reason it doesn't load the Nether at all.

I haven't noticed this problem until this point because I did all major testing in a Superflat world and in that occasion everything work as intended. I tried to reproduce the bug on a Superflat world but nothing strange happened, but when I tried on another normal world the same issue happened again.

Another thing that I noticed was that the tips from the mod "Tips" weren't showing up during the "Loading terrain..." phase, if this can be of any help.

I can't provide any crash log because the game simply doesn't crash and stays stuck in eternal loading.

**Comment by Mrbysco** [comment]
I've just uploaded a new version, once it becomes available could you test it to see if the bug has been fixed?

**Comment by ShadowDeltaQ** [comment]
Perfectly fixed!
