### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by KateHanami** [Mrbysco/Dimensional-Paintings#14]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

I would like to have this mod to be compatible with immersive portals, having that mod makes so you can seamlessly move to any (compatible) dimension without any loading screens by having all dimensions rendering together

**Comment by Mrbysco** [comment]
That's out of the scope of this mod
