### ISSUE TITLE
Painting isn't a full portal, just one spot above it.

### ISSUE THREAD

**Issue by VallenFrostweaver** [Mrbysco/Dimensional-Paintings#2]
Minecraft 1.16.5
Forge 36.1.30
Dimensional Paintings 1.16.5
JEI 7.7.0.104
Placebo 4.5.0
Toast Control 4.3.1

I can't walk through any painting unless I jump at this specific block spot while in front of the painting.
![image](https://user-images.githubusercontent.com/13642054/121339818-c8c8d300-c916-11eb-9bc6-3a6dad9279de.png)

**Comment by Mrbysco** [comment]
The jumping in is intended. It's a nod to Super Mario 64

**Comment by Mrbysco** [comment]
It's that way also to stop accidental entering of the dimension while just walking by
