### ISSUE TITLE
[Bug]: Dimensional Painting pops off and is sent through itself to another dimension

### ISSUE THREAD

**Issue by Raidobw2** [Mrbysco/Dimensional-Paintings#4]
## General Info
<!-->
- [x] I am running a modpack
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I am using the latest version of the mod

## Client Info
* Minecraft Version: 1.16.5

* Forge Version: 36.2.8
* Mod Version: Dimensional-Paintings-1.16.5-1.1.2.jar
* Java Version: Unknown/8u51
* Modpack: FTB OceanBlock 1.5.0

## Issue Description
We were trying to figure out how to use dimensional paintings, and trying different ways to make it work. I picked up and put down the painting, and my partner said "I wonder if we have to walk through it?"

He was behind the wall and broke the block behind it, which would cause a typical painting to pop off the wall. Instead, it totally disappeared! It's not the end of the world because we aren't hurting for resources, just a pain.

We built a 1 deep, 6 across, 4 tall wall of Cobble that had been chiseled to Tiles, and built stone brick stairs up to the level of the painting.

I placed it in the middle and breaking the block one in from the corner broke the painting.

```
WWWWWW
WPPPPW
WPPXPW
WWWWWW
```

(this is the wall, the X is where we broke)

He also broke the block above that first and it didn't affect the painting.

We both logged out and reloaded the world, to no avail.

## Reproduce Steps
((We have not tried it more than once))

1. Create wall with chiseled cobble
2. Place painting on wall
3. Break block painting was placed against

## Expected Behavior
Painting pops off and is NOT destroyed

## Additional Information
UPDATE: So I made another one and went through the portal (after watching videos on how to) and my other nether portal painting was there, on the other side.

I'm relaying this issue from FTBTeam/FTB-Modpack-Issues#220
User is running FTB OceanBlock 1.5.0 on a server with a friend.
Please let me know if you think your mod is not the issue so I can try to look into other solutions perhaps.
Thank you!

**Comment by Mrbysco** [comment]
Apparently I forgot to check if the painting entity was still alive while doing collision checks meaning it was going into itself instantly

**Comment by Raidobw2** [comment]
That was indeed a funny interaction. Thank you for the very quick reply and fix :)
